name: Test

on:
  pull_request:

env:
  DEFAULT_PYTHON: 3.6

jobs:
  test:
    runs-on: ubuntu-20.04
    name: Test
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          cache: pip
      - name: Install dependencies (pip)
        run: python -m pip install -r requirements.txt -r testing-requirements.txt
      - name: Test
        run: make test

# vim:ts=2:sw=2:et
